package ru.kc4kt4.students.test.model.exception

class AuthException : RuntimeException()